# Veterinary Clinical Data Analysis with Pandas

This project demonstrates foundational data analysis skills using Python and pandas. The objective is to load, clean, validate, and explore a veterinary clinical dataset while applying common data analyst workflows.

In [239]:
import pandas as pd

In [240]:
import numpy as np

In [241]:
df = pd.read_csv('/content/veterinary_clinical_data.csv')

In [242]:
df

,AnimalName,Breed,Age,Weight_kg,MedicalHistory,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,6.0,32.1,Chronic illness,Anorexia,Hydrophobia,drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,9.9,18.5,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,13.9,18.9,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,cat,Scottish Fold,5.8,6.3,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,cat,Persian,11.2,4.9,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor Body condition
...,...,...,...,...,...,...,...,...,...,...
9995,cat,British Shorthair,11.8,4.5,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea
9996,cat,Scottish Fold,3.3,6.4,Recent surgery,Sneezing,Diarrhea,swollen lymph nodes,Diarrhea,Vomiting
9997,Dog,Golden Retriever,9.6,40.6,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia
9998,Dog,Labrador Retriever,11.7,37.5,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints
9999,Dog,Boxer,13.7,26.3,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin

## Initial Data Exploration

Review the dataset structure, column names, data types, and summary statistics to understand the available data and identify potential cleaning requirements.

In [243]:
df.head()

,AnimalName,Breed,Age,Weight_kg,MedicalHistory,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,6.0,32.1,Chronic illness,Anorexia,Hydrophobia,drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,9.9,18.5,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,13.9,18.9,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,cat,Scottish Fold,5.8,6.3,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,cat,Persian,11.2,4.9,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor Body condition

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   AnimalName      10000 non-null  object
 1   Breed           10000 non-null  object
 2   Age             10000 non-null  float64
 3   Weight_kg       10000 non-null  float64
 4   MedicalHistory  10000 non-null  object
 5   Symptom_1       10000 non-null  object
 6   Symptom_2       10000 non-null  object
 7   Symptom_3       10000 non-null  object
 8   Symptom_4       10000 non-null  object
 9   Symptom_5       10000 non-null  object
dtypes: float64(2), object(8)
memory usage: 781.4+ KB

In [245]:
df.describe()

                Age     Weight_kg
count  10000.000000  10000.000000
mean       8.428050     14.891990
std        4.639286     12.624691
min        0.500000      2.500000
25%        4.800000      5.300000
50%        8.400000      7.300000
75%       12.000000     25.500000
max       18.000000     45.000000

## Data Cleaning

Standardize column names and values to improve consistency and prepare the dataset for analysis.

In [246]:
df.rename({'AnimalName': 'Species'}, axis=1, inplace = True)

In [247]:
df

,Species,Breed,Age,Weight_kg,MedicalHistory,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,6.0,32.1,Chronic illness,Anorexia,Hydrophobia,drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,9.9,18.5,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,13.9,18.9,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,cat,Scottish Fold,5.8,6.3,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,cat,Persian,11.2,4.9,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor Body condition
...,...,...,...,...,...,...,...,...,...,...
9995,cat,British Shorthair,11.8,4.5,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea
9996,cat,Scottish Fold,3.3,6.4,Recent surgery,Sneezing,Diarrhea,swollen lymph nodes,Diarrhea,Vomiting
9997,Dog,Golden Retriever,9.6,40.6,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia
9998,Dog,Labrador Retriever,11.7,37.5,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints
9999,Dog,Boxer,13.7,26.3,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin

In [248]:
df['Species'] = df['Species'].replace('cat', 'Cat')

In [249]:
df

,Species,Breed,Age,Weight_kg,MedicalHistory,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,6.0,32.1,Chronic illness,Anorexia,Hydrophobia,drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,9.9,18.5,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,13.9,18.9,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,Cat,Scottish Fold,5.8,6.3,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,Cat,Persian,11.2,4.9,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor Body condition
...,...,...,...,...,...,...,...,...,...,...
9995,Cat,British Shorthair,11.8,4.5,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea
9996,Cat,Scottish Fold,3.3,6.4,Recent surgery,Sneezing,Diarrhea,swollen lymph nodes,Diarrhea,Vomiting
9997,Dog,Golden Retriever,9.6,40.6,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia
9998,Dog,Labrador Retriever,11.7,37.5,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints
9999,Dog,Boxer,13.7,26.3,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin

### Create Derived Columns

Convert weight measurements from kilograms to pounds to make the data easier to interpret and analyze.

In [250]:
df['Weight_lbs'] = (df['Weight_kg'] * 2.2046).round(1)

In [251]:
df

,Species,Breed,Age,Weight_kg,MedicalHistory,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Weight_lbs
0,Dog,Rottweiler,6.0,32.1,Chronic illness,Anorexia,Hydrophobia,drooping ears,Diarrhea,Shyness or aggression,70.8
1,Dog,Bulldog,9.9,18.5,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing,40.8
2,Dog,Beagle,13.9,18.9,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production,41.7
3,Cat,Scottish Fold,5.8,6.3,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness,13.9
4,Cat,Persian,11.2,4.9,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor Body condition,10.8
...,...,...,...,...,...,...,...,...,...,...,...
9995,Cat,British Shorthair,11.8,4.5,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea,9.9
9996,Cat,Scottish Fold,3.3,6.4,Recent surgery,Sneezing,Diarrhea,swollen lymph nodes,Diarrhea,Vomiting,14.1
9997,Dog,Golden Retriever,9.6,40.6,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia,89.5
9998,Dog,Labrador Retriever,11.7,37.5,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints,82.7
9999,Dog,Boxer,13.7,26.3,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin,58.0

### Reorganize Dataset Structure

Move the newly created Weight_lbs column to a more logical position within the dataset for readability.

In [252]:
column_to_move = df.pop('Weight_lbs')

In [253]:
df.insert(4, 'Weight_lbs', column_to_move)

In [254]:
df

,Species,Breed,Age,Weight_kg,Weight_lbs,MedicalHistory,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,6.0,32.1,70.8,Chronic illness,Anorexia,Hydrophobia,drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,9.9,18.5,40.8,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,13.9,18.9,41.7,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,Cat,Scottish Fold,5.8,6.3,13.9,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,Cat,Persian,11.2,4.9,10.8,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor Body condition
...,...,...,...,...,...,...,...,...,...,...,...
9995,Cat,British Shorthair,11.8,4.5,9.9,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea
9996,Cat,Scottish Fold,3.3,6.4,14.1,Recent surgery,Sneezing,Diarrhea,swollen lymph nodes,Diarrhea,Vomiting
9997,Dog,Golden Retriever,9.6,40.6,89.5,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia
9998,Dog,Labrador Retriever,11.7,37.5,82.7,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints
9999,Dog,Boxer,13.7,26.3,58.0,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin

### Standardize Text Values

Apply consistent capitalization across categorical fields to eliminate duplicate categories caused by formatting differences.

In [255]:
columns_to_capitalize = ['Species', 'Breed', 'MedicalHistory','Symptom_1','Symptom_2','Symptom_3','Symptom_4','Symptom_5']
df[columns_to_capitalize] = df[columns_to_capitalize].apply(lambda x: x.str.capitalize())
df[columns_to_capitalize]

,Species,Breed,MedicalHistory,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,Chronic illness,Anorexia,Hydrophobia,Drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,Cat,Scottish fold,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,Cat,Persian,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor body condition
...,...,...,...,...,...,...,...,...
9995,Cat,British shorthair,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea
9996,Cat,Scottish fold,Recent surgery,Sneezing,Diarrhea,Swollen lymph nodes,Diarrhea,Vomiting
9997,Dog,Golden retriever,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia
9998,Dog,Labrador retriever,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints
9999,Dog,Boxer,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin

### Improve Column Naming

Rename columns to follow a more consistent naming convention.

In [256]:
df.rename({'MedicalHistory': 'Medical_History'}, axis=1, inplace = True)

In [257]:
df

,Species,Breed,Age,Weight_kg,Weight_lbs,Medical_History,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,6.0,32.1,70.8,Chronic illness,Anorexia,Hydrophobia,Drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,9.9,18.5,40.8,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,13.9,18.9,41.7,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,Cat,Scottish fold,5.8,6.3,13.9,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,Cat,Persian,11.2,4.9,10.8,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor body condition
...,...,...,...,...,...,...,...,...,...,...,...
9995,Cat,British shorthair,11.8,4.5,9.9,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea
9996,Cat,Scottish fold,3.3,6.4,14.1,Recent surgery,Sneezing,Diarrhea,Swollen lymph nodes,Diarrhea,Vomiting
9997,Dog,Golden retriever,9.6,40.6,89.5,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia
9998,Dog,Labrador retriever,11.7,37.5,82.7,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints
9999,Dog,Boxer,13.7,26.3,58.0,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin

## Data Quality Assessment

Check the dataset for missing values and potential data quality issues.

In [258]:
df.isnull().sum()

Species            0
Breed              0
Age                0
Weight_kg          0
Weight_lbs         0
Medical_History    0
Symptom_1          0
Symptom_2          0
Symptom_3          0
Symptom_4          0
Symptom_5          0
dtype: int64

### Duplicate Record Review

Identify duplicate records that may impact reporting accuracy and investigate whether they represent true duplicates or valid repeated observations.

In [259]:
df.duplicated().sum()

np.int64(20)

In [260]:
duplicates = df[df.duplicated(keep=False)]
duplicates.head()

,Species,Breed,Age,Weight_kg,Weight_lbs,Medical_History,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
135,Cat,Siamese,8.2,5.0,11.0,No previous conditions,Lession on cat skin,Dandruff in cat coat,Red patches,Hair loss,Skin issue
444,Cat,Scottish fold,9.7,6.8,15.0,Parasite history,Emaciation,Difficulty in breathing,Vomiting,Weakness,Diarrhea
461,Dog,Beagle,3.0,15.8,34.8,Vaccinated,Allergic reaction,Poor appetite,Coughing,Weight loss,Distended chest
531,Cat,Bengal,0.7,4.9,10.8,Dental issues,Nasal bleeding,Diffulty chewing,Swelling,Weight loss,Anorexia
992,Cat,Maine coon,0.7,6.5,14.3,Dental issues,Fever,Dyspnea,Coughing,Weakness,Anorexia

## Exploratory Data Analysis

Examine the distribution of animals by species to better understand the composition of the dataset.

In [261]:
df['Species'].value_counts(normalize=True)

Species
Dog    0.502
Cat    0.498
Name: proportion, dtype: float64

### Filter Data by Age

Review records for animals older than five years to explore age-related characteristics.

In [262]:
df[df['Age'] > 5]

,Species,Breed,Age,Weight_kg,Weight_lbs,Medical_History,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
0,Dog,Rottweiler,6.0,32.1,70.8,Chronic illness,Anorexia,Hydrophobia,Drooping ears,Diarrhea,Shyness or aggression
1,Dog,Bulldog,9.9,18.5,40.8,Vaccinated,Lethargy,Weakness,Horny growth,Fever,Coughing
2,Dog,Beagle,13.9,18.9,41.7,Parasite history,Pain,Weight loss,Weight loss,Sneezing,Drop on egg production
3,Cat,Scottish fold,5.8,6.3,13.9,Recent surgery,Vomiting,Pain,Edema in lower jaw,Pain,Weakness
4,Cat,Persian,11.2,4.9,10.8,Recent surgery,Severe,Weight loss,Egg production stops,Weakness,Poor body condition
...,...,...,...,...,...,...,...,...,...,...,...
9994,Cat,Mixed breed,9.2,5.7,12.6,Allergies,Urination problem,Stand with head droping,Diarrhea,Coughing,Painfull swalling
9995,Cat,British shorthair,11.8,4.5,9.9,No previous conditions,No appp,Coughing,Fever,Weight loss,Diarrhea
9997,Dog,Golden retriever,9.6,40.6,89.5,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia
9998,Dog,Labrador retriever,11.7,37.5,82.7,No previous conditions,Fever,Loss of appetite,Coughing,Lameness,Swelling of joints
9999,Dog,Boxer,13.7,26.3,58.0,Not vaccinated,Blood in urine,Diarrhea,Vomiting,Lethargy,Bleeding in eye and skin

### Filter by Medical Conditions

Identify patients with selected medical histories for targeted analysis.

In [263]:
df[df['Medical_History'].isin(['Allergies', 'Dental issues'])]

,Species,Breed,Age,Weight_kg,Weight_lbs,Medical_History,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
6,Dog,Boxer,2.6,27.6,60.8,Dental issues,Indigestion,Abdminal pain,Constipation,Diarrhea,Nausea
9,Dog,Beagle,1.7,16.2,35.7,Allergies,Fever,Loss of appetite,Reduce energy,Lameness,Swelling of joints
24,Dog,Rottweiler,2.8,25.0,55.1,Dental issues,Weight loss,Fever,Fever,Vomiting,Fever
26,Dog,Boxer,9.2,24.1,53.1,Dental issues,Weight loss,Fever,Pain,Poor immune function,Inflammed eye
29,Dog,Yorkshire terrier,13.2,7.3,16.1,Allergies,Fever,Loss of appetite,Depression,Loss of appetite,Pains
...,...,...,...,...,...,...,...,...,...,...,...
9976,Dog,Beagle,1.4,19.6,43.2,Allergies,Vomiting,Anorexia,Fever,Sneezing,Difficulty breating
9978,Dog,German shepherd,9.8,38.0,83.8,Dental issues,Swelling on leg,Painfull,Nasal discharge,Broken bones,Nasal discharge
9980,Cat,Maine coon,17.0,8.3,18.3,Allergies,Coughing,Pain,Weight loss,Vomiting,Self-isolation
9994,Cat,Mixed breed,9.2,5.7,12.6,Allergies,Urination problem,Stand with head droping,Diarrhea,Coughing,Painfull swalling
9997,Dog,Golden retriever,9.6,40.6,89.5,Dental issues,Fever,Vomiting,Anorexia,Weakness,Anorexia

### Multi-Condition Filtering

Apply multiple filtering conditions to locate specific subsets of records.

In [264]:
df[(df['Species'] == 'Dog') & (df['Symptom_1'] == 'Vomiting')]

,Species,Breed,Age,Weight_kg,Weight_lbs,Medical_History,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5
13,Dog,Yorkshire terrier,11.0,5.1,11.2,Parasite history,Vomiting,Pain,Fever,Weight loss,Anorexia
115,Dog,Labrador retriever,8.0,29.9,65.9,Previous kidney disease,Vomiting,Weakness,Coughing,Sneezing,Pain
166,Dog,Beagle,3.7,25.8,56.9,Recent surgery,Vomiting,Diarrhea,Dehydration,Weight loss,Poor coat apperence
199,Dog,Labrador retriever,3.5,42.7,94.1,Chronic illness,Vomiting,Weight loss,Drooling,Sneezing,Coughing
223,Dog,Bulldog,5.3,23.1,50.9,Chronic illness,Vomiting,Fever,Anorexia,Poor appetite,Weakness
...,...,...,...,...,...,...,...,...,...,...,...
9861,Dog,Golden retriever,0.5,31.9,70.3,Dental issues,Vomiting,Pain,Fever,Fever,Fever
9869,Dog,Beagle,8.5,15.4,34.0,Recent surgery,Vomiting,Diarrhea,Coughing,Fever,Fever
9878,Dog,Poodle,14.7,4.9,10.8,Not vaccinated,Vomiting,Vomiting,Weight loss,Weight loss,Lethargy
9976,Dog,Beagle,1.4,19.6,43.2,Allergies,Vomiting,Anorexia,Fever,Sneezing,Difficulty breating
9982,Dog,Golden retriever,8.3,25.9,57.1,Previous heart condition,Vomiting,Vomiting,Anorexia,Fever,Bleeding from the nose

### Average Age by Species

Calculate average age for each species using groupby aggregation.

In [265]:
df.groupby('Species')['Age'].mean().round(0)

Species
Cat    9.0
Dog    7.0
Name: Age, dtype: float64

### Average Weight by Species

Compare average weight across species to identify differences between animal groups.

In [266]:
df.groupby('Species')['Weight_lbs'].mean().round(2)

Species
Cat    12.17
Dog    53.32
Name: Weight_lbs, dtype: float64

### Medical History Frequency

Determine the most common medical conditions represented in the dataset.

In [267]:
df.groupby('Medical_History').size().sort_values(ascending=False)

Medical_History
Skin conditions history     1017
No previous conditions       995
Recent surgery               953
Chronic illness              940
Not vaccinated               922
Allergies                    897
Dental issues                889
Parasite history             888
Previous kidney disease      870
Vaccinated                   832
Previous heart condition     797
dtype: int64

### Most Common Breeds

Identify the most frequently occurring breeds within the dataset.

In [268]:
df['Breed'].value_counts().head(10)

Breed
Mixed breed        1105
Ragdoll             620
Bengal              614
Siamese             584
Scottish fold       572
Bulldog             559
Rottweiler          557
German shepherd     535
Maine coon          515
Sphynx              511
Name: count, dtype: int64

# Key Findings
---

*   Dogs represented the largest share of patients in the dataset.
*   Labrador Retrievers were the most common breed.
*   Average weight differed significantly between species.
*   Several medical conditions appeared repeatedly, including allergies and dental issues.
*   The dataset contained 20 duplicate records that were investigated during the data quality review process.
*   Basic exploratory analysis helped summarize trends within the dataset.